site_name: Patlab
site_description: Generate text-based patterns easily in Python
site_url: https://sayampradhan.github.io/patlab/

repo_url: https://github.com/sayampradhan/patlab/
repo_name: Patlab

theme:
  name: material
  logo: images/logo_resized.png
  favicon: images/favicon.ico

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest

  palette:
    - scheme: default
      primary: "#2563EB"
      accent: "#60A5FA"

    - scheme: slate
      primary: "#2563EB"
      accent: "#60A5FA"

plugins:
  - search

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Patterns:
      - Square: patterns/square.md
      - Pyramid: patterns/pyramid.md
      - Right Triangle: patterns/triangle.md

extra:
  palette:
    primary: "#2563EB"
    accent: "#60A5FA"

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sayampradhan/patlab

    - icon: fontawesome/solid/download
      link: https://pypi.org/project/patlab/